"""Link table

Revision ID: a6ea05bfbf3c
Revises: 
Create Date: 2023-01-31 15:40:15.007729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ea05bfbf3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short', sa.String(length=6), nullable=True),
    sa.Column('link_url', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_link_url'), ['link_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_link_short'), ['short'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_short'))
        batch_op.drop_index(batch_op.f('ix_link_link_url'))

    op.drop_table('link')
    # ### end Alembic commands ###
